import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  const { step, topic } = await request.json();
  
  console.log('🎭 Demo mode: Executing step:', step.title, 'for topic:', topic);
  
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 800));
  
  const demoContent = `
# ${step.title} Analysis for ${topic}

## Overview
This is a comprehensive analysis of ${step.title} in the context of ${topic}. In a real research scenario, this content would be generated by AI based on extensive knowledge analysis.

## Key Insights
- **Current Market Position**: ${topic} shows significant growth and innovation potential
- **Technical Developments**: Latest advancements demonstrate improved efficiency and capabilities  
- **Industry Trends**: Market adoption is accelerating with increasing consumer interest
- **Competitive Landscape**: Multiple players are investing heavily in this space

## Detailed Analysis
The research into ${step.title} reveals several important considerations:

1. **Performance Metrics**: Current benchmarks show competitive advantages in key areas
2. **Cost Considerations**: Pricing strategies vary significantly across different segments
3. **User Adoption**: Consumer feedback indicates positive reception with room for improvement
4. **Technology Evolution**: Rapid advancement in underlying technologies

## Research Findings
Based on the analysis of ${step.title}:

- Market demand continues to grow at approximately 15-20% annually
- Key technological barriers are being addressed through innovation
- Consumer preferences are shifting toward more advanced solutions
- Investment in research and development remains robust

## Implications for ${topic}
This research step provides valuable insights into the broader landscape of ${topic}, highlighting opportunities for growth, potential challenges to address, and strategic considerations for future development.

## Recommendations
1. Continue monitoring technological developments in this area
2. Assess competitive positioning relative to emerging trends
3. Consider user feedback in product development decisions
4. Evaluate cost-benefit implications of implementation
  `;

  const mockSources = [
    {
      title: `${step.title} Research Analysis - ${topic}`,
      link: `#demo-${step.title.toLowerCase().replace(/\s+/g, '-')}`,
      snippet: `Comprehensive analysis of ${step.title} aspects related to ${topic} research.`
    },
    {
      title: `${topic} Market Study - ${step.title} Focus`,
      link: `#demo-market-${topic.toLowerCase().replace(/\s+/g, '-')}`,
      snippet: `Market research focusing on ${step.title} within the ${topic} domain.`
    }
  ];
  
  return NextResponse.json({
    content: demoContent,
    sources: mockSources,
    timestamp: new Date().toISOString(),
    searchPerformed: false,
    isRealAPI: false,
    demoMode: true,
    step: step.title,
    topic: topic
  });
}
